apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: gitlab-helm-repo
        namespace: flux-system
      chart: gitlab-runner
      version: 0.64.1  # Ensure this is the correct new version
  releaseName: gitlab-runner
  install:
    remediation:
      retries: 3
  values:
    image:
      registry: artifactory.mda.mil
      image: gm-tma-docker-prod-local/gitlab-runner
      tag: release  # Update to the latest version
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - name: "pull-secret"
    gitlabUrl: https://gitlab.mda.mil
    unregisterRunners: true
    terminationGracePeriodSeconds: 3600
    concurrent: 45
    checkInterval: 5
    sessionServer:
      enabled: false
    rbac:
      create: true
      clusterWideAccess: false
      serviceAccountName: infra-gitlab-runner
    metrics:
      enabled: false
    service:
      enabled: false
      type: ClusterIP
    runners:
      secret: gitlab-runner-secret
      config: |
        [[runners]]
          builds_dir = "/tmp"
          environment = ["HOME=/tmp"]
          [runners.kubernetes]
            namespace = "{{.Release.Namespace}}"
            image = "artifactory.mda.mil/gm-tma-docker-prod-local/custom/custom-az-tf-alpine:v0.0.2"
            image_pull_secrets = ["pull-secret"]
            helper_image_flavor = "ubi-fips"
            helper_image = "artifactory.mda.mil/gm-tma-docker-prod-local/gitlab-runner-helper:release"
            pull_policy = "always"
            dns_policy = "cluster-first-with-host-net"
            node_selector:
              "agentpool" = "runner"
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    podSecurityContext:
      runAsUser: 998
      runAsGroup: 995
      fsGroup: 0
    resources:
      limits:
        memory: 2048M
        cpu: 1000m
      requests:
        memory: 1024M
        cpu: 500m
    nodeSelector:
      agentpool: "user"
    volumeMounts:
      - mountPath: /tmp
        name: tmp
    volumes:
      - emptyDir: {}
        name: tmp